### ISSUE TITLE
Sources for Project:

### ISSUE THREAD

**Issue by dylanmore** [dylanmore/operation-barbarossa#2]
Below, our sources for the "Operation Barbarossa Project" will be listed.

**Comment by dylanmore** [comment]
I believe that this should be our main source for dates of importance. We should pull information from this timeline, highlight certain things, and then locate sources that go into more depth on battles that we believe are important to discuss in more depth.
[Holocaust Research Project](http://www.holocaustresearchproject.org/nazioccupation/opbarb.html)

**Comment by dylanmore** [comment]
[Britannica Academic](https://academic.eb.com/levels/collegiate/article/Operation-Barbarossa/545372)

**Comment by mattnowakowski** [comment]
[Operation Barbarossa : Nazi Germany's War in the East](https://ebookcentral.proquest.com/lib/pitt-ebooks/reader.action?docID=1179555
)
[Operation Barbarossa and Germany's Defeat in the East](https://ebookcentral.proquest.com/lib/pitt-ebooks/reader.action?docID=1303580)
